<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AppSettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('app_settings')->delete();

        \DB::table('app_settings')->insert( array(
            array('id' => '7','key' => 'date_format','value' => 'l jS F Y (H:i:s)'),
            array('id' => '8','key' => 'language','value' => 'en'),
            array('id' => '17','key' => 'is_human_date_format','value' => '1'),
            array('id' => '18','key' => 'app_name','value' => 'Grounded Goodness Private Limited'),
            array('id' => '19','key' => 'app_short_description','value' => 'Manage Mobile Application'),
            array('id' => '20','key' => 'mail_driver','value' => 'smtp'),
            array('id' => '21','key' => 'mail_host','value' => 'mail.s22beta.com.au'),
            array('id' => '22','key' => 'mail_port','value' => '465'),
            array('id' => '23','key' => 'mail_username','value' => 'info@s22beta.com.au'),
            array('id' => '24','key' => 'mail_password','value' => 'l]_,h*bRSjDp'),
            array('id' => '25','key' => 'mail_encryption','value' => 'ssl'),
            array('id' => '26','key' => 'mail_from_address','value' => 'info@s22beta.com.au'),
            array('id' => '27','key' => 'mail_from_name','value' => 'Grounded Goodness Pvt Ltd'),
            array('id' => '30','key' => 'timezone','value' => 'Asia/Kolkata'),
            array('id' => '32','key' => 'theme_contrast','value' => 'dark'),
            array('id' => '33','key' => 'theme_color','value' => 'success'),
            array('id' => '34','key' => 'app_logo','value' => '81392723-971b-4c96-92dc-719ebbc49e3b'),
            array('id' => '35','key' => 'nav_color','value' => 'navbar-dark bg-success'),
            array('id' => '38','key' => 'logo_bg_color','value' => 'bg-white'),
            array('id' => '66','key' => 'default_role','value' => 'admin'),
            array('id' => '68','key' => 'facebook_app_id','value' => '518416208939727'),
            array('id' => '69','key' => 'facebook_app_secret','value' => '93649810f78fa9ca0d48972fee2a75cd'),
            array('id' => '71','key' => 'twitter_app_id','value' => 'twitter'),
            array('id' => '72','key' => 'twitter_app_secret','value' => 'twitter 1'),
            array('id' => '74','key' => 'google_app_id','value' => '527129559488-roolg8aq110p8r1q952fqa9tm06gbloe.apps.googleusercontent.com'),
            array('id' => '75','key' => 'google_app_secret','value' => 'FpIi8SLgc69ZWodk-xHaOrxn'),
            array('id' => '77','key' => 'enable_google','value' => '0'),
            array('id' => '78','key' => 'enable_facebook','value' => '0'),
            array('id' => '93','key' => 'enable_stripe','value' => '1'),
            array('id' => '94','key' => 'stripe_key','value' => 'pk_test_pltzOnX3zsUZMoTTTVUL4O41'),
            array('id' => '95','key' => 'stripe_secret','value' => 'sk_test_o98VZx3RKDUytaokX4My3a20'),
            array('id' => '104','key' => 'default_tax','value' => '10'),
            array('id' => '107','key' => 'default_currency','value' => '₹'),
            array('id' => '108','key' => 'fixed_header','value' => 'fixed-top'),
            array('id' => '109','key' => 'fixed_footer','value' => '0'),
            array('id' => '110','key' => 'fcm_key','value' => 'AAAAHedj3dM:APA91bHIIhWsOlgw50nI__jHr2Zg8PhQqAr1OCmVQQIaLd90rcqbydecizB053-EnKDCfPiyHMWU8vkYjUABTcu8dUBTJP065ggIxDmNCsZGgTm8eAg2SnduMZ1aPYVd-UhKJsuIKvsZ'),
            array('id' => '111','key' => 'enable_notifications','value' => '1'),
            array('id' => '112','key' => 'paypal_username','value' => 'sb-z3gdq482047_api1.business.example.com'),
            array('id' => '113','key' => 'paypal_password','value' => 'JV2A7G4SEMLMZ565'),
            array('id' => '114','key' => 'paypal_secret','value' => 'AbMmSXVaig1ExpY3utVS3dcAjx7nAHH0utrZsUN6LYwPgo7wfMzrV5WZ'),
            array('id' => '115','key' => 'enable_paypal','value' => '1'),
            array('id' => '116','key' => 'main_color','value' => '#455817'),
            array('id' => '117','key' => 'main_dark_color','value' => '#455817'),
            array('id' => '118','key' => 'second_color','value' => '#103c2e'),
            array('id' => '119','key' => 'second_dark_color','value' => '#ccccdd'),
            array('id' => '120','key' => 'accent_color','value' => '#8c98a8'),
            array('id' => '121','key' => 'accent_dark_color','value' => '#9999aa'),
            array('id' => '122','key' => 'scaffold_dark_color','value' => '#2c2c2c'),
            array('id' => '123','key' => 'scaffold_color','value' => '#fafafa'),
            array('id' => '124','key' => 'google_maps_key','value' => 'AIzaSyBO_gULxLbNl0_4Bo-SBCjszpdb_6Ig6QM'),
            array('id' => '125','key' => 'mobile_language','value' => 'en'),
            array('id' => '126','key' => 'app_version','value' => '2.0.0'),
            array('id' => '127','key' => 'enable_version','value' => '0'),
            array('id' => '128','key' => 'default_currency_id','value' => '3'),
            array('id' => '129','key' => 'default_currency_code','value' => 'INR'),
            array('id' => '130','key' => 'default_currency_decimal_digits','value' => '2'),
            array('id' => '131','key' => 'default_currency_rounding','value' => '0'),
            array('id' => '132','key' => 'currency_right','value' => '0'),
            array('id' => '157','key' => 'app_store_address_line_1','value' => '1 Main Street'),
            array('id' => '158','key' => 'app_store_address_line_2','value' => 'Freddie Mountains'),
            array('id' => '159','key' => 'app_store_city','value' => 'Aliceland'),
            array('id' => '160','key' => 'app_store_pincode','value' => '380004'),
            array('id' => '161','key' => 'app_store_state','value' => 'GUJARAT'),
            array('id' => '162','key' => 'app_store_country','value' => 'INDIA'),
            array('id' => '163','key' => 'app_store_phone_no','value' => '8888888888'),
            array('id' => '164','key' => 'app_store_gstin','value' => '22AABCU9603R1ZX'),
            array('id' => '165','key' => 'app_invoice_signature','value' => '0'),
            array('id' => '166','key' => 'app_invoice_color','value' => '#01422a'),
            array('id' => '167','key' => 'app_invoice_theme','value' => '1'),
            array('id' => '168','key' => 'app_bank_bankname','value' => 'SBI'),
            array('id' => '169','key' => 'app_bank_account_number','value' => '123456789101212341345'),
            array('id' => '170','key' => 'app_bank_ifsc_code','value' => 'SBI0021312'),
            array('id' => '171','key' => 'app_bank_bankbranch','value' => 'COIMBATORE'),
            array('id' => '172','key' => 'app_upi_id','value' => 'itzmyrulz37@okhdfcbank.com'),
            array('id' => '173','key' => 'app_upi_code','value' => '75402c5e-62bd-4e73-bc27-8831afa32aef'),
            array('id' => '174','key' => 'app_thermal_print','value' => '2'),
            array('id' => '175','key' => 'app_invoice_terms_and_conditions','value' => '<p>Orders placed post 2:00 PM will be dispatched the next day. We appreciate you patience and we thank you for you business.  </p>'),
            array('id' => '176','key' => 'files','value' => '0'),
            array('id' => '177','key' => 'app_invoice_prefix','value' => 'GGPL-2021'),
            array('id' => '178','key' => 'home_section_1','value' => 'search'),
            array('id' => '179','key' => 'home_section_2','value' => 'slider'),
            array('id' => '180','key' => 'home_section_3','value' => 'categories_heading'),
            array('id' => '181','key' => 'home_section_4','value' => 'categories'),
            array('id' => '182','key' => 'home_section_5','value' => 'trending_week_heading'),
            array('id' => '183','key' => 'home_section_6','value' => 'trending_week'),
            array('id' => '184','key' => 'home_section_7','value' => 'special_offer_heading'),
            array('id' => '185','key' => 'home_section_8','value' => 'special_offer'),
            array('id' => '186','key' => 'home_section_9','value' => 'recent_reviews_heading'),
            array('id' => '187','key' => 'home_section_10','value' => 'recent_reviews'),
            array('id' => '188','key' => 'home_section_11','value' => 'empty'),
            array('id' => '189','key' => 'home_section_12','value' => 'empty'),
            array('id' => '190','key' => 'firebase_api_key','value' => 'AIzaSyBO_gULxLbNl0_4Bo-SBCjszpdb_6Ig6QM'),
            array('id' => '191','key' => 'firebase_auth_domain','value' => 'ggpl-f43f1.firebaseapp.com'),
            array('id' => '192','key' => 'firebase_database_url','value' => 'https://ggpl-f43f1-default-rtdb.firebaseio.com/'),
            array('id' => '193','key' => 'firebase_project_id','value' => 'ggpl-f43f1'),
            array('id' => '194','key' => 'firebase_storage_bucket','value' => 'ggpl-f43f1.appspot.com'),
            array('id' => '195','key' => 'firebase_messaging_sender_id','value' => '128436133331'),
            array('id' => '196','key' => 'firebase_app_id','value' => '1:128436133331:web:21d1aba6090fed64b46326'),
            array('id' => '197','key' => 'firebase_measurement_id','value' => 'G-9E32HC3Y6H'),
            array('id' => '198','key' => 'enable_twitter','value' => '0'),
            array('id' => '199','key' => 'app_facebook_url','value' => 'https://www.facebook.com/'),
            array('id' => '200','key' => 'app_instagram_url','value' => 'https://www.instagram.com/'),
            array('id' => '201','key' => 'app_linkedin_url','value' => 'https://www.linkedin.com/'),
            array('id' => '202','key' => 'app_twitter_url','value' => 'https://twitter.com/'),
            array('id' => '203','key' => 'app_website_email','value' => 'info@ggpl.com'),
            array('id' => '204','key' => 'app_website_mobile','value' => '+91 9876543210'),
            array('id' => '205','key' => 'app_website_volunteer','value' => '<p></p><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book<br></p><p></p>'),
            array('id' => '206','key' => 'app_website_aboutus','value' => 'Grounded Goodness Private Limited
            Spare more with ‘Grounded Goodness Private Limited’ ! We give you the most minimal costs on the entirety of your grocery needs.
            Grounded Goodness Private Limited is a low-cost online general store that gets items crosswise over classifications like grocery, natural products and vegetables, excellence and health, family unit care, infant care, pet consideration  conveyed to your doorstep.'),
            array('id' => '207','key' => 'app_website_android_url','value' => 'https://play.google.com/'),
            array('id' => '208','key' => 'app_website_ios_url','value' => 'https://play.google.com/'),
            array('id' => '209','key' => 'google_api_key','value' => 'AIzaSyBO_gULxLbNl0_4Bo-SBCjszpdb_6Ig6QM'),
            array('id' => '210','key' => 'app_store_latitude','value' => '10.99343489263872'),
            array('id' => '211','key' => 'app_store_longitude','value' => '76.96163177490236'),
            array('id' => '212','key' => 'distance_unit','value' => 'km'),
            array('id' => '213','key' => 'global_reward_status','value' => '1'),
            array('id' => '214','key' => 'app_referal_reward_points','value' => '1000'),
            array('id' => '215','key' => 'app_charity_contribution','value' => '1'),
            array('id' => '216','key' => 'birthday_discount','value' => '10'),
            array('id' => '217','key' => 'home_section_13','value' => 'standard_products_heading'),
            array('id' => '218','key' => 'home_section_14','value' => 'standard_products'),
            array('id' => '219','key' => 'home_section_15','value' => 'organic_products_heading'),
            array('id' => '220','key' => 'home_section_16','value' => 'organic_products'),
            array('id' => '221','key' => 'home_section_17','value' => 'gmo_products_heading'),
            array('id' => '222','key' => 'home_section_18','value' => 'gmo_products'),
            array('id' => '223','key' => 'home_section_19','value' => 'high_volume_products_heading'),
            array('id' => '224','key' => 'home_section_20','value' => 'high_volume_products'),
            array('id' => '225','key' => 'home_section_21','value' => 'confectionaries_heading'),
            array('id' => '226','key' => 'home_section_22','value' => 'confectionaries'),
            array('id' => '227','key' => 'home_section_23','value' => 'non_gmo_products_heading'),
            array('id' => '228','key' => 'home_section_24','value' => 'non_gmo_products'),
            array('id' => '229','key' => 'home_section_25','value' => 'value_added_products_heading'),
            array('id' => '230','key' => 'home_section_26','value' => 'value_added_products'),
            array('id' => '231','key' => 'app_email_header_image','value' => '0')
        ) );
    }
}
